name: Push Branch

on:
  push:
    branches:
      - '*'

env: {}

jobs:
  get-date:
    name: Date
    uses: silnith/github-workflows/.github/workflows/bash-get-date.yaml@main

  maven-cache:
    name: Maven Cache
    permissions:
      contents: read
      packages: read
    needs:
      - get-date
    uses: silnith/github-workflows/.github/workflows/maven-cache-dependencies.yaml@main
    with:
      directory: java/solitaire
      year: ${{ needs.get-date.outputs.year }}
      month: ${{ needs.get-date.outputs.month }}
      day: ${{ needs.get-date.outputs.day }}
    secrets: inherit
  maven-verify:
    name: Maven
    permissions:
      contents: read
      packages: read
    needs:
      - get-date
      - maven-cache
    uses: silnith/github-workflows/.github/workflows/maven-verify.yaml@main
    with:
      artifact-prefix: maven
      directory: java/solitaire
      year: ${{ needs.get-date.outputs.year }}
      month: ${{ needs.get-date.outputs.month }}
      day: ${{ needs.get-date.outputs.day }}
    secrets: inherit
  maven-test-results:
    name: Maven Test Results
    permissions:
      contents: read
      issues: read
      checks: write
    needs:
      - maven-verify
    uses: silnith/github-workflows/.github/workflows/publish-test-results.yaml@main
    with:
      check-name: Java Test Results
      artifact-pattern: maven-target
      artifact-path: java/solitaire
      test-result-files: |
        java/solitaire/**/target/surefire-reports/TEST-*.xml
        java/solitaire/**/target/failsafe-reports/TEST-*.xml
    secrets: inherit

  dotnet-cache:
    name: .NET Cache
    permissions:
      contents: read
      packages: read
    needs:
      - get-date
    uses: silnith/github-workflows/.github/workflows/dotnet-cache-dependencies.yaml@main
    with:
      directory: csharp/Solitaire
      solution-file: Solitaire.sln
      dotnet-versions: 5.x
      year: ${{ needs.get-date.outputs.year }}
      month: ${{ needs.get-date.outputs.month }}
      day: ${{ needs.get-date.outputs.day }}
    secrets: inherit
  dotnet-build:
    name: .NET
    permissions:
      contents: read
      packages: read
    needs:
      - get-date
      - dotnet-cache
    strategy:
      matrix:
        configuration:
          - Debug
          - Release
    uses: silnith/github-workflows/.github/workflows/dotnet-build.yaml@main
    with:
      artifact-prefix: dotnet
      directory: csharp/Solitaire
      solution-file: Solitaire.sln
      configuration: ${{ matrix.configuration }}
      dotnet-versions: 5.x
      year: ${{ needs.get-date.outputs.year }}
      month: ${{ needs.get-date.outputs.month }}
      day: ${{ needs.get-date.outputs.day }}
    secrets: inherit
  dotnet-test-results:
    name: .NET Test Results
    permissions:
      contents: read
      issues: read
      checks: write
    needs:
      - dotnet-build
    uses: silnith/github-workflows/.github/workflows/publish-test-results.yaml@main
    with:
      check-name: C# Test Results
      artifact-pattern: dotnet-test-*
      artifact-path: csharp/Solitaire
      test-result-files: csharp/Solitaire/**/TestResults/**/*.trx
    secrets: inherit

  nuget-cache:
    name: NuGet Cache
    permissions:
      contents: read
      packages: read
    needs:
      - get-date
    uses: silnith/github-workflows/.github/workflows/nuget-cache-dependencies.yaml@main
    with:
      directory: cpp/Solitaire
      solution-file: Solitaire.sln
      year: ${{ needs.get-date.outputs.year }}
      month: ${{ needs.get-date.outputs.month }}
      day: ${{ needs.get-date.outputs.day }}
    secrets: inherit
  msbuild-intel:
    name: C++ Intel
    permissions:
      contents: read
      packages: read
    needs:
      - get-date
      - nuget-cache
    strategy:
      matrix:
        platform:
          - x86
          - x64
        configuration:
          - Debug
          - Release
    uses: silnith/github-workflows/.github/workflows/msbuild-intel.yaml@main
    with:
      artifact-prefix: msbuild
      directory: cpp/Solitaire
      solution-file: Solitaire.sln
      platform: ${{ matrix.platform }}
      configuration: ${{ matrix.configuration }}
      year: ${{ needs.get-date.outputs.year }}
      month: ${{ needs.get-date.outputs.month }}
      day: ${{ needs.get-date.outputs.day }}
    secrets: inherit
  msbuild-arm:
    name: C++ ARM
    permissions:
      contents: read
      packages: read
    needs:
      - get-date
      - nuget-cache
    strategy:
      matrix:
        platform:
          - ARM
          - ARM64
        configuration:
          - Debug
          - Release
    uses: silnith/github-workflows/.github/workflows/msbuild-arm.yaml@main
    with:
      artifact-prefix: msbuild
      directory: cpp/Solitaire
      solution-file: Solitaire.sln
      platform: ${{ matrix.platform }}
      configuration: ${{ matrix.configuration }}
      year: ${{ needs.get-date.outputs.year }}
      month: ${{ needs.get-date.outputs.month }}
      day: ${{ needs.get-date.outputs.day }}
    secrets: inherit
  vstest-results:
    name: VSTest Results
    permissions:
      contents: read
      issues: read
      checks: write
    needs:
      - msbuild-intel
      - msbuild-arm
    uses: silnith/github-workflows/.github/workflows/publish-test-results.yaml@main
    with:
      check-name: C++ Test Results
      artifact-pattern: msbuild-vstest-*
      artifact-path: cpp/Solitaire
      test-result-files: |
        cpp/Solitaire/**/TestResults/**/*.trx
    secrets: inherit
