name: Push Branch

on:
  push:
    branches:
      - '*'

env: {}

jobs:
  get-date:
    name: Date
    uses: silnith/github-workflows/.github/workflows/bash-get-date.yaml@single-publish-test-results

  maven-cache:
    name: Maven Cache
    needs:
      - get-date
    uses: silnith/github-workflows/.github/workflows/maven-cache-dependencies.yaml@single-publish-test-results
    with:
      directory: java/solitaire
      year: ${{ needs.get-date.outputs.year }}
      month: ${{ needs.get-date.outputs.month }}
      day: ${{ needs.get-date.outputs.day }}
    secrets: inherit
    permissions:
      contents: read
  maven-build:
    name: Maven
    needs:
      - get-date
      - maven-cache
    uses: silnith/github-workflows/.github/workflows/maven-verify.yaml@single-publish-test-results
    with:
      artifact-prefix: java
      directory: java/solitaire
      year: ${{ needs.get-date.outputs.year }}
      month: ${{ needs.get-date.outputs.month }}
      day: ${{ needs.get-date.outputs.day }}
    secrets: inherit
    permissions:
      contents: read
      checks: write
  maven-test-results:
    name: Publish Maven Test Results
    needs:
      - maven-build
    uses: silnith/github-workflows/.github/workflows/publish-test-results.yaml@single-publish-test-results
    with:
      check-name: Java Test Results
      artifact-pattern: java-target
      artifact-path: java/solitaire
      test-result-files: |
        java/solitaire/**/target/surefire-reports/TEST-*.xml
        java/solitaire/**/target/failsafe-reports/TEST-*.xml
    secrets: inherit
    permissions:
      checks: write

  dotnet-cache:
    name: .NET Cache
    needs:
      - get-date
    uses: silnith/github-workflows/.github/workflows/dotnet-cache-dependencies.yaml@single-publish-test-results
    with:
      directory: csharp/Solitaire
      solution-file: Solitaire.sln
      dotnet-versions: 5.x
      year: ${{ needs.get-date.outputs.year }}
      month: ${{ needs.get-date.outputs.month }}
      day: ${{ needs.get-date.outputs.day }}
    secrets: inherit
    permissions:
      contents: read
  dotnet-build:
    name: .NET
    needs:
      - get-date
      - dotnet-cache
    strategy:
      matrix:
        configuration:
          - Debug
          - Release
    uses: silnith/github-workflows/.github/workflows/dotnet-build.yaml@single-publish-test-results
    with:
      artifact-prefix: csharp
      directory: csharp/Solitaire
      solution-file: Solitaire.sln
      configuration: ${{ matrix.configuration }}
      dotnet-versions: 5.x
      year: ${{ needs.get-date.outputs.year }}
      month: ${{ needs.get-date.outputs.month }}
      day: ${{ needs.get-date.outputs.day }}
    secrets: inherit
    permissions:
      contents: read
  dotnet-test-results:
    name: Publish .NET Test Results
    needs:
      - dotnet-build
    uses: silnith/github-workflows/.github/workflows/publish-test-results.yaml@single-publish-test-results
    with:
      check-name: .NET Test Results
      artifact-pattern: csharp-dotnet-test-results-*
      artifact-path: csharp/Solitaire
      test-result-files: csharp/Solitaire/**/TestResults/**/*.trx
    secrets: inherit
    permissions:
      checks: write

  build-cpp:
    name: C++
    uses: ./.github/workflows/run-msbuild.yaml
    with:
      name: cpp
      directory: cpp/Solitaire
      solution_file: Solitaire.sln
    secrets: inherit
    permissions:
      contents: read
      checks: write
