name: Push Branch

on:
  push:
    branches:
      - '*'

env: {}

jobs:
  build-cpp:
    name: Build C++
    uses: ./.github/workflows/run-msbuild.yaml
    with:
      name: cpp
      directory: cpp/Solitaire
      solution_file: Solitaire.sln
    secrets: inherit
    permissions:
      contents: read
  build-csharp:
    name: Build C#
    uses: ./.github/workflows/run-dotnet.yaml
    with:
      name: csharp
      directory: csharp/Solitaire
      solution_file: Solitaire.sln
    secrets: inherit
    permissions:
      contents: read
      checks: write
  build-java:
    name: Build Java
    uses: ./.github/workflows/run-maven.yaml
    with:
      directory: java/solitaire
    secrets: inherit
    permissions:
      contents: read
      packages: write
      checks: write
