name: Push Branch

on:
  push:
    branches:
      - '*'

env: {}

jobs:
  get-date:
    name: Date
    uses: silnith/github-workflows/.github/workflows/bash-get-date.yaml@main
  maven-cache:
    name: Maven Cache
    needs:
      - get-date
    uses: silnith/github-workflows/.github/workflows/maven-cache-dependencies.yaml@main
    with:
      directory: java/solitaire
      year: ${{ needs.get-date.outputs.year }}
      month: ${{ needs.get-date.outputs.month }}
      day: ${{ needs.get-date.outputs.day }}
    secrets: inherit
    permissions:
      contents: read
  maven-build:
    name: Maven
    needs:
      - get-date
      - maven-cache
    uses: silnith/github-workflows/.github/workflows/maven-verify.yaml@main
    with:
      artifact-prefix: java
      directory: java/solitaire
      year: ${{ needs.get-date.outputs.year }}
      month: ${{ needs.get-date.outputs.month }}
      day: ${{ needs.get-date.outputs.day }}
    secrets: inherit
    permissions:
      contents: read
      checks: write
  build-cpp:
    name: C++
    uses: ./.github/workflows/run-msbuild.yaml
    with:
      name: cpp
      directory: cpp/Solitaire
      solution_file: Solitaire.sln
    secrets: inherit
    permissions:
      contents: read
      checks: write
  build-csharp:
    name: C#
    uses: ./.github/workflows/run-dotnet.yaml
    with:
      name: csharp
      directory: csharp/Solitaire
      solution_file: Solitaire.sln
    secrets: inherit
    permissions:
      contents: read
      checks: write
