name: Run .NET

on:
  workflow_call:
    inputs:
      name:
        description: A prefix for artifact names.
        type: string
        required: true
      directory:
        description: The directory that contains the solution file.
        type: string
        required: true
      solution_file:
        description: The name of the solution file.
        type: string
        required: true

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  setup:
    name: Setup
    runs-on: windows-2022
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            5.x
            6.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: NuGet Tool Restore
        run: dotnet tool restore
      - name: NuGet Restore
        run: dotnet restore ${{ inputs.solution_file }}
      - name: Upload Packages Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}-packages
          path: ~/.nuget/packages/
          if-no-files-found: error
  build:
    name: Build
    runs-on: windows-2022
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    needs:
      - setup
    strategy:
      matrix:
        configuration:
          - Debug
          - Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            5.x
            6.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download Packages Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.name }}-packages
          path: ~/.nuget/packages/
      - name: Build
        run: dotnet build ${{ inputs.solution_file }} --configuration ${{ matrix.configuration }}
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}-${{ matrix.configuration }}
          # This action does not respect the working directory.
          path: |
            ${{ inputs.directory }}/**/bin/
            ${{ inputs.directory }}/**/obj/
          if-no-files-found: error
  test:
    name: Test
    runs-on: windows-2022
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    needs:
      - build
    strategy:
      matrix:
        configuration:
          - Debug
          - Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            5.x
            6.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download Packages Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.name }}-packages
          path: ~/.nuget/packages/
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.name }}-${{ matrix.configuration }}
          # This action does not respect the working directory.
          path: ${{ inputs.directory }}/
      - name: Test
        run: dotnet test ${{ inputs.solution_file }} --configuration ${{ matrix.configuration }} --collect "XPlat Code Coverage"
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        continue-on-error: true
        with:
          files: |
            **/TestResults/**/*.xml
            **/TestResults/**/*.trx
          comment_mode: off
